name: Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Use Node.js LTS
      uses: actions/setup-node@v5
      with:
        node-version: 'lts/*'

    - name: "Build libmongocrypt"
      shell: bash
      run: |
        npm run install:libmongocrypt

    - name: "Install dependencies"
      shell: bash
      run: |
        npm install

    - name: "Install dependencies in the Webpack bundle test package"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm install

    - name: "Install local mongodb-client-encryption into Webpack bundle test package"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm run install:ce

    - name: "Run webpack build"
      shell: bash
      working-directory: ./test/bundling/webpack
      run: |
        npm run build